apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: authority-webserver
  annotations:
    flux.weave.works/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-webserver
  chart:
    path: examples/identity-app/charts/webserver
    git: ssh://git@github.com/VladimirDzamba/blockchain-automation-framework.git
    ref: development-environment
  values:
    metadata:
      namespace: authority-ns
      name: authority-webserver
    organization:
      name: authority
    image:
      pullSecret: regcred
      init:
        name: authority-webserver-init
        repository: alpine:3.9.4
      server:
        name: authority-webserver
        repository: build.dev.di-uisp-accenture.com/von-network-base:1.11.0
    service:
      port: 18005
    vault:
      address: http://192.168.99.209:16196
      serviceAccountName: authority-authority-trustee-vault-auth
      authPath: kubernetes-authority-authority-trustee-auth
      trusteeName: authority-trustee
      role: ro
    storage:
      size: 128Mi
      className: authority-minikube-storageclass
